vich_uploader:
    db_driver: orm

    mappings:
        possession_image:
            uri_prefix: /images/possessions
            upload_destination: '%kernel.project_dir%/public/images/possessions'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true