vich_uploader:
    db_driver: orm

    mappings:
        possession_image:
            uri_prefix: /images/possessions
            upload_destination: '%kernel.project_dir%/public/images/possessions'
            namer: Vich\UploaderBundle\Naming\OrignameNamer